from __future__ import annotations

from src.generator.block_renderer import render_blocks
from src.generator.inline_renderer import _escape_typst_string
from src.models.project import ProjectFile
from src.models.theme import Theme


def _render_meta(meta) -> str:
    # Typst dictionary literal
    parts: list[str] = [
        f'id: "{_escape_typst_string(meta.id)}"',
        f'title: "{_escape_typst_string(meta.title)}"',
        f'author: "{_escape_typst_string(meta.author)}"',
        f'language: "{_escape_typst_string(meta.language)}"',
        f'direction: "{_escape_typst_string(meta.direction)}"',
    ]
    if meta.subtitle:
        parts.append(f'subtitle: "{_escape_typst_string(meta.subtitle)}"')
    if meta.version:
        parts.append(f'version: "{_escape_typst_string(meta.version)}"')
    if meta.created_at:
        parts.append(f'created_at: "{_escape_typst_string(meta.created_at)}"')
    if meta.updated_at:
        parts.append(f'updated_at: "{_escape_typst_string(meta.updated_at)}"')
    return "(" + ", ".join(parts) + ")"


def _render_theme(theme: Theme) -> str:
    # Emit a Typst dictionary literal that matches templates/macros.typ expectations.
    margin = theme.page.margin_mm
    page = (
        f'(size: "{theme.page.size}", dpi: {theme.page.dpi}, '
        f"margin_mm: (top: {margin.top}, right: {margin.right}, bottom: {margin.bottom}, left: {margin.left}))"
    )

    fonts_parts = [f'base: "{_escape_typst_string(theme.fonts.base)}"', f'mono: "{_escape_typst_string(theme.fonts.mono)}"']
    if theme.fonts.math:
        fonts_parts.append(f'math: "{_escape_typst_string(theme.fonts.math)}"')
    fonts = "(" + ", ".join(fonts_parts) + ")"

    colors = (
        "("
        + ", ".join(
            [
                f'text: "{theme.colors.text}"',
                f'background: "{theme.colors.background}"',
                f'muted: "{theme.colors.muted}"',
                f'accent: "{theme.colors.accent}"',
                f'border: "{theme.colors.border}"',
                f'code_bg: "{theme.colors.code_bg}"',
            ]
        )
        + ")"
    )

    text = (
        f"(base_size_px: {theme.text.base_size_px}, line_height: {theme.text.line_height})"
        if theme.text
        else "none"
    )

    ltr_inline_style = "none"
    if theme.ltr_inline_style:
        t = theme.ltr_inline_style
        parts = []
        if t.boxed_border_color:
            parts.append(f'boxed_border_color: "{t.boxed_border_color}"')
        if t.boxed_background:
            parts.append(f'boxed_background: "{t.boxed_background}"')
        if t.mono_background:
            parts.append(f'mono_background: "{t.mono_background}"')
        ltr_inline_style = "(" + ", ".join(parts) + ")" if parts else "none"

    # Optional theme substructures are passed through as none for now (keeps template stable).
    return (
        "("
        + ", ".join(
            [
                f"page: {page}",
                f"fonts: {fonts}",
                f"colors: {colors}",
                f"text: {text}",
                "headings: none",
                "code: none",
                "tables: none",
                f"ltr_inline_style: {ltr_inline_style}",
            ]
        )
        + ")"
    )


def render_project_file(pf: ProjectFile) -> str:
    project = pf.project
    meta = _render_meta(project.meta)
    theme = _render_theme(project.theme)

    body_parts: list[str] = []
    for s in project.subjects:
        body_parts.append(f"// subject:{s.id} title:{s.title}\n")
        body_parts.append(render_blocks(s.blocks))

    body = "\n".join(body_parts).strip() + "\n"

    return (
        "// Generated by SDRE (Phase 3). Do not edit.\n\n"
        f"#let meta = {meta}\n"
        f"#let theme = {theme}\n\n"
        "#sdre_document(meta, theme)[\n"
        f"{body}"
        "]\n"
    )

